export const CURRENCY_LIST_FETCH = 'CURRENCY_LIST_FETCH';
export const CURRENCY_LIST_SUCCESS = 'CURRENCY_LIST_SUCCESS';
export const CURRENCY_LIST_FAIL = 'CURRENCY_LIST_FAIL';
export const CURRENCY_LIST_CANCEL = 'CURRENCY_LIST_CANCEL';