export const CURRENCY_LIST_FETCH = 'CURRENCY_LIST_FETCH';
export const CURRENCY_LIST_SUCCESS = 'CURRENCY_LIST_SUCCESS';
export const CURRENCY_LIST_FAIL = 'CURRENCY_LIST_FAIL';
export const CURRENCY_LIST_CANCEL = 'CURRENCY_LIST_CANCEL';
export const CURRENCY_LIST_UPDATE = 'CURRENCY_LIST_UPDATE';
export const CURRENCY_LIST_UPDATE_SUCCESS = 'CURRENCY_LIST_UPDATE_SUCCESS';

export const WITHDRAW_FETCH = 'WITHDRAW_FETCH';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_FAIL = 'WITHDRAW_FAIL';