export const START_FETCH_DATA = 'START_FETCH_DATA';
export const CANCEL_FETCH_DATA = 'CANCEL_FETCH_DATA';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
