export const USER_REGISTER_EMAIL = 'USER_REGISTER_EMAIL';
export const USER_REGISTER_PHONE = 'USER_REGISTER_PHONE';
export const USER_CREATE_TOKEN = 'USER_CREATE_TOKEN';
export const USER_VERIFY_TOKEN = 'USER_VERIFY_TOKEN';
export const USER_LOGIN_EMAIL = 'USER_LOGIN_EMAIL';
export const USER_LOGIN_PHONE = 'USER_LOGIN_PHONE';
export const USER_AUTH_SUCCESS = 'USE_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USE_AUTH_FAIL';

export const USER_VERIFY_FAIL = 'USER_VERIFY_FAIL';
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS';
export const USER_RENEW_TOKEN = 'USER_RENEW_TOKEN';
export const USER_VERIFY_CANCEL = 'USER_VERIFY_CANCEL';

export const USER_PROFILE_FETCH = 'USER_PROFILE_FETCH';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const AUTH_CHECK = 'AUTH_CHECK';